language: python
cache: pip

matrix:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9"
  - python: pypy3
  - env: TOX_ENV=pep8
  - env: TOX_ENV=pylint
  - env: TOX_ENV=coverage

# commands to install dependencies
install:
  - pip install -U tox-travis

# commands to run
script:
  - tox

after_success:
  - if [ "-x$TOX_ENV" = "xcoverage" ]; then coveralls; fi
